### ISSUE TITLE
Introduce UI for SYSMON Start/stop

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/deepsee-sysmon-dashboards#9]

**Comment by eduard93** [comment]
For this and https://github.com/intersystems-ru/deepsee-sysmon-dashboards/issues/10
Is it going to be a separate application? 
Or a special dashboard with buttons - custom cube actions?

**Comment by MakarovS96** [comment]
Вероятно это будет отдельное веб приложение основанное на REST. Но пока рано говорить, Возможно после курсов DeepSee будет рассмотрен вариант с приборной панелью.
